const videosArray = [
  {
    title: "test1",
    author: "601dd8dc2424e92775ccc007",
    source: "https://www.w3schools.com/html/movie.mp4",
    duration: 12.612,
    date: null,
    ratio: "0:1",
    extension: "601fb254c947832e9cbd086a",
    details: {
      streams: [
        {
          index: 0,
          codec_name: "h264",
          codec_long_name: "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
          profile: "Constrained Baseline",
          codec_type: "video",
          codec_time_base: "3153/187000",
          codec_tag_string: "avc1",
          codec_tag: "0x31637661",
          width: 320,
          height: 240,
          coded_width: 320,
          coded_height: 240,
          has_b_frames: 0,
          sample_aspect_ratio: "0:1",
          display_aspect_ratio: "0:1",
          pix_fmt: "yuv420p",
          level: 13,
          color_range: "tv",
          color_space: "smpte170m",
          color_transfer: "bt709",
          color_primaries: "smpte170m",
          chroma_location: "left",
          field_order: "unknown",
          timecode: "N/A",
          refs: 1,
          is_avc: "true",
          nal_length_size: 4,
          id: "N/A",
          r_frame_rate: "30000/1001",
          avg_frame_rate: "93500/3153",
          time_base: "1/90000",
          start_pts: 0,
          start_time: 0,
          duration_ts: 1135080,
          duration: 12.612,
          bit_rate: 80637,
          max_bit_rate: "N/A",
          bits_per_raw_sample: 8,
          nb_frames: 374,
          nb_read_frames: "N/A",
          nb_read_packets: "N/A",
          tags: [Object],
          disposition: [Object],
        },
        {
          index: 1,
          codec_name: "aac",
          codec_long_name: "AAC (Advanced Audio Coding)",
          profile: "LC",
          codec_type: "audio",
          codec_time_base: "1/48000",
          codec_tag_string: "mp4a",
          codec_tag: "0x6134706d",
          sample_fmt: "fltp",
          sample_rate: 48000,
          channels: 2,
          channel_layout: "stereo",
          bits_per_sample: 0,
          id: "N/A",
          r_frame_rate: "0/0",
          avg_frame_rate: "0/0",
          time_base: "1/48000",
          start_pts: 0,
          start_time: 0,
          duration_ts: 605184,
          duration: 12.608,
          bit_rate: 115752,
          max_bit_rate: 119080,
          bits_per_raw_sample: "N/A",
          nb_frames: 591,
          nb_read_frames: "N/A",
          nb_read_packets: "N/A",
          tags: [Object],
          disposition: [Object],
        },
        {
          index: 2,
          codec_name: "bin_data",
          codec_long_name: "binary data",
          profile: "unknown",
          codec_type: "data",
          codec_tag_string: "text",
          codec_tag: "0x74786574",
          id: "N/A",
          r_frame_rate: "0/0",
          avg_frame_rate: "0/0",
          time_base: "1/90000",
          start_pts: 0,
          start_time: 0,
          duration_ts: 1135080,
          duration: 12.612,
          bit_rate: 8,
          max_bit_rate: "N/A",
          bits_per_raw_sample: "N/A",
          nb_frames: 1,
          nb_read_frames: "N/A",
          nb_read_packets: "N/A",
          tags: [Object],
          disposition: [Object],
        },
      ],
      format: {
        filename: "https://www.w3schools.com/html/movie.mp4",
        nb_streams: 3,
        nb_programs: 0,
        format_name: "mov,mp4,m4a,3gp,3g2,mj2",
        format_long_name: "QuickTime / MOV",
        start_time: 0,
        duration: 12.612,
        size: 318465,
        bit_rate: 202007,
        probe_score: 100,
        tags: {
          major_brand: "mp42",
          minor_version: "0",
          compatible_brands: "mp42isomavc1",
          creation_time: "2010-05-11T10:32:06.000000Z",
          encoder: "HandBrake 0.9.4 2009112300",
        },
      },
      chapters: [],
    },
  },
  {
    title: "test2",
    author: "601dd8dc2424e92775ccc007",
    source: "https://www.w3schools.com/html/mov_bbb.mp4",
    duration: 10.026667,
    date: null,
    ratio: "0:1",
    extension: "601fb254c947832e9cbd086a",
    details: {
      streams: [
        {
          index: 0,
          codec_name: "h264",
          codec_long_name: "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
          profile: "Main",
          codec_type: "video",
          codec_time_base: "1/50",
          codec_tag_string: "avc1",
          codec_tag: "0x31637661",
          width: 320,
          height: 176,
          coded_width: 320,
          coded_height: 176,
          has_b_frames: 2,
          sample_aspect_ratio: "0:1",
          display_aspect_ratio: "0:1",
          pix_fmt: "yuv420p",
          level: 12,
          color_range: "tv",
          color_space: "smpte170m",
          color_transfer: "bt709",
          color_primaries: "smpte170m",
          chroma_location: "left",
          field_order: "unknown",
          timecode: "N/A",
          refs: 1,
          is_avc: "true",
          nal_length_size: 4,
          id: "N/A",
          r_frame_rate: "25/1",
          avg_frame_rate: "25/1",
          time_base: "1/90000",
          start_pts: 0,
          start_time: 0,
          duration_ts: 900000,
          duration: 10,
          bit_rate: 300570,
          max_bit_rate: "N/A",
          bits_per_raw_sample: 8,
          nb_frames: 250,
          nb_read_frames: "N/A",
          nb_read_packets: "N/A",
          tags: [Object],
          disposition: [Object],
        },
        {
          index: 1,
          codec_name: "aac",
          codec_long_name: "AAC (Advanced Audio Coding)",
          profile: "LC",
          codec_type: "audio",
          codec_time_base: "1/48000",
          codec_tag_string: "mp4a",
          codec_tag: "0x6134706d",
          sample_fmt: "fltp",
          sample_rate: 48000,
          channels: 2,
          channel_layout: "stereo",
          bits_per_sample: 0,
          id: "N/A",
          r_frame_rate: "0/0",
          avg_frame_rate: "0/0",
          time_base: "1/48000",
          start_pts: 0,
          start_time: 0,
          duration_ts: 481280,
          duration: 10.026667,
          bit_rate: 160545,
          max_bit_rate: 175528,
          bits_per_raw_sample: "N/A",
          nb_frames: 470,
          nb_read_frames: "N/A",
          nb_read_packets: "N/A",
          tags: [Object],
          disposition: [Object],
        },
        {
          index: 2,
          codec_name: "aac",
          codec_long_name: "AAC (Advanced Audio Coding)",
          profile: "LC",
          codec_type: "audio",
          codec_time_base: "1/48000",
          codec_tag_string: "mp4a",
          codec_tag: "0x6134706d",
          sample_fmt: "fltp",
          sample_rate: 48000,
          channels: 2,
          channel_layout: "stereo",
          bits_per_sample: 0,
          id: "N/A",
          r_frame_rate: "0/0",
          avg_frame_rate: "0/0",
          time_base: "1/48000",
          start_pts: 0,
          start_time: 0,
          duration_ts: 481280,
          duration: 10.026667,
          bit_rate: 160580,
          max_bit_rate: 175512,
          bits_per_raw_sample: "N/A",
          nb_frames: 470,
          nb_read_frames: "N/A",
          nb_read_packets: "N/A",
          tags: [Object],
          disposition: [Object],
        },
        {
          index: 3,
          codec_name: "bin_data",
          codec_long_name: "binary data",
          profile: "unknown",
          codec_type: "data",
          codec_tag_string: "text",
          codec_tag: "0x74786574",
          id: "N/A",
          r_frame_rate: "0/0",
          avg_frame_rate: "0/0",
          time_base: "1/90000",
          start_pts: 0,
          start_time: 0,
          duration_ts: 902400,
          duration: 10.026667,
          bit_rate: 18,
          max_bit_rate: "N/A",
          bits_per_raw_sample: "N/A",
          nb_frames: 1,
          nb_read_frames: "N/A",
          nb_read_packets: "N/A",
          tags: [Object],
          disposition: [Object],
        },
      ],
      format: {
        filename: "https://www.w3schools.com/html/mov_bbb.mp4",
        nb_streams: 4,
        nb_programs: 0,
        format_name: "mov,mp4,m4a,3gp,3g2,mj2",
        format_long_name: "QuickTime / MOV",
        start_time: 0,
        duration: 10.026667,
        size: 788493,
        bit_rate: 629116,
        probe_score: 100,
        tags: {
          major_brand: "mp42",
          minor_version: "0",
          compatible_brands: "mp42isomavc1",
          creation_time: "2012-03-13T08:58:06.000000Z",
          encoder: "HandBrake 0.9.6 2012022800",
        },
      },
      chapters: [],
    },
  },
];

module.exports = videosArray;
